function matlabTest
% add the paths you'll need
addpath('/home/sadacca/HMM/Functions',...
    '/home/sadacca/HMM/Sadacca',...
    '/home/sadacca/HMM/Results',...
    '/home/sadacca/HMM/Results/AllData',...
    '/home/sadacca/HMM/Sadacca/SpikeData',...
    '/home/sadacca/HMM/Results/AllData/',...
    '/home/sadacca/HMM/Results/newresults1ms/');
dir('/home/sadacca/HMM/Functions/')
RunMain()
dir('/home/sadacca/HMM/Results/newresults1ms')
save THESPIKEDATA